### ISSUE TITLE
Harfbuzz dependency chafa not found

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/smith#67]
Have configured my [provision.sh](https://github.com/silnrsi/smith/blob/master/vm-install/focal/provision.sh) to install Graphite and Harfbuzz from source. I'm getting this error during Harfbuzz build:
```
    default: Run-time dependency cairo-ft found: YES 1.16.0
    default: Found CMake: /usr/bin/cmake (3.16.3)
    default: Run-time dependency chafa found: NO (tried pkgconfig and cmake)
    default:
    default: meson.build:157:0: ERROR: Dependency "chafa" not found, tried pkgconfig and cmake
    default:
    default: A full log can be found at /home/vagrant/srcbuilds/harfbuzz/build/meson-logs/meson-log.txt
```
BdV says chafa is a relatively new dependency for Harfbuzz
